### ISSUE TITLE
Steps to build node-packer from releases?

### ISSUE THREAD

**Issue by kgunnar** [slee047/node-packer#6]
Hi,

Are there specific steps to compile the releases into an executable? The README.md just mentions downloading the pre-built one from enclose.io but nothing about creating a nodec binary from the release source code. Thanks!

**Comment by saurabh-deep** [comment]
+1

**Comment by saurabh-deep** [comment]
Hey @slee047! I was able to build nodec successfully on Mac using ruby-packer. But I am unable to build the same on Windows. I know you have put the Windows details in [how.to.setup.nodec.txt](https://github.com/slee047/node-packer/blob/master/how.to.setup.nodec.txt), but I am unable to clone from git@gitlab.sft.asia:high-assurance-guard/nodec.git.

Will you be able to help with the Windows build. I need it to work.

**Comment by slee047** [comment]
Sorry, the how.to.setup.nodec.txt is a draft document that should not be in the repo. I shall improve on the documentation by next Monday if possible.

**Comment by saurabh-deep** [comment]
That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.

**Comment by slee047** [comment]
> That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.

Well, you need to download the zip file:
https://github.com/slee047/node-packer/archive/1.6.0-8.15.1.zip

Then, you will extract this zip file to any folder (portable), for example, C:\nodec

Now, the entry path (Where executable is located) is at: C:\nodec\bin\nodec
The bat file is not really necessary if you have the SquashFS, and Ruby installed.

**Comment by kgunnar** [comment]
> > That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.
> 
> Before proceed on, I have assumed that you have installed the dependencies (SquashFS, Ruby and Python 2.7.x and added them into PATH environment variable)
> 
> Next, you will need to download the zip file (With 8.15.1 runtime):
> https://github.com/slee047/node-packer/archive/1.6.0-8.15.1.zip
> 
> Then, you will extract this zip file to any folder (portable), for example, C:\nodec
> 
> Now, the entry path (Where executable is located) is at: C:\nodec\bin\nodec
> The bat file is not really necessary if you have the SquashFS, and Ruby installed.
> 
> Subsequently, it is recommended for you to add the path (C:\nodec\bin) into PATH environment variable, so that your script can invoke this with 'nodec'.
> 
> Lastly, if you have a valid Node.js application (With package.json etc.), then it should compile the Node.js application with correct command use.
> 
> For start, I compile my Node.js application with this command:
> 
> ruby "nodec" --make-args=j8 -d "%TEMPPATH%" -r "%SRCPATH%" -o "%BINPATH%\output.exe" "%SRCPATH%\main.js"
> 
> Where:
> 
> * TEMPPATH = A temporary folder to store compilation cache, which takes several GBs.
> * SRCPATH = Path to the root source code directory (Project directory)
> * BINPATH = Path to the installed folder
> 
> And that:
> 
> * The Windows Node.js executable program is named as output.exe
> * The entry point of this application is located on main.js

This seems to be instructions to build a separate application? My original question was how to turn the archive into a more portable/unified nodec binary rather than running the ruby script directly. Essentially how to build this nodec/node-packer into an executable rather than how to use the source to build a separate app into an executable? Sorry if it wasn't clear. Thanks

**Comment by slee047** [comment]
> > > That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.
> > 
> > 
> > Before proceed on, I have assumed that you have installed the dependencies (SquashFS, Ruby and Python 2.7.x and added them into PATH environment variable)
> > Next, you will need to download the zip file (With 8.15.1 runtime):
> > https://github.com/slee047/node-packer/archive/1.6.0-8.15.1.zip
> > Then, you will extract this zip file to any folder (portable), for example, C:\nodec
> > Now, the entry path (Where executable is located) is at: C:\nodec\bin\nodec
> > The bat file is not really necessary if you have the SquashFS, and Ruby installed.
> > Subsequently, it is recommended for you to add the path (C:\nodec\bin) into PATH environment variable, so that your script can invoke this with 'nodec'.
> > Lastly, if you have a valid Node.js application (With package.json etc.), then it should compile the Node.js application with correct command use.
> > For start, I compile my Node.js application with this command:
> > ruby "nodec" --make-args=j8 -d "%TEMPPATH%" -r "%SRCPATH%" -o "%BINPATH%\output.exe" "%SRCPATH%\main.js"
> > Where:
> > 
> > * TEMPPATH = A temporary folder to store compilation cache, which takes several GBs.
> > * SRCPATH = Path to the root source code directory (Project directory)
> > * BINPATH = Path to the installed folder
> > 
> > And that:
> > 
> > * The Windows Node.js executable program is named as output.exe
> > * The entry point of this application is located on main.js
> 
> This seems to be instructions to build a separate application? My original question was how to turn the archive into a more portable/unified nodec binary rather than running the ruby script directly. Essentially how to build this nodec/node-packer into an executable rather than how to use the source to build a separate app into an executable? Sorry if it wasn't clear. Thanks

Sorry, I think I misunderstood the question as well. Well, the original author managed to compiled it as an executable per README.md, but it has not been updated for 2 years or so and still points to earlier nodec 1.5.0 that bundles with Node.js 8.3.0.

I have no idea how to compile this into a binary file for Windows, macOS and Linux too.....

**Comment by saurabh-deep** [comment]
> > > > That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.
> > > 
> > > 
> > > Before proceed on, I have assumed that you have installed the dependencies (SquashFS, Ruby and Python 2.7.x and added them into PATH environment variable)
> > > Next, you will need to download the zip file (With 8.15.1 runtime):
> > > https://github.com/slee047/node-packer/archive/1.6.0-8.15.1.zip
> > > Then, you will extract this zip file to any folder (portable), for example, C:\nodec
> > > Now, the entry path (Where executable is located) is at: C:\nodec\bin\nodec
> > > The bat file is not really necessary if you have the SquashFS, and Ruby installed.
> > > Subsequently, it is recommended for you to add the path (C:\nodec\bin) into PATH environment variable, so that your script can invoke this with 'nodec'.
> > > Lastly, if you have a valid Node.js application (With package.json etc.), then it should compile the Node.js application with correct command use.
> > > For start, I compile my Node.js application with this command:
> > > ruby "nodec" --make-args=j8 -d "%TEMPPATH%" -r "%SRCPATH%" -o "%BINPATH%\output.exe" "%SRCPATH%\main.js"
> > > Where:
> > > 
> > > * TEMPPATH = A temporary folder to store compilation cache, which takes several GBs.
> > > * SRCPATH = Path to the root source code directory (Project directory)
> > > * BINPATH = Path to the installed folder
> > > 
> > > And that:
> > > 
> > > * The Windows Node.js executable program is named as output.exe
> > > * The entry point of this application is located on main.js
> > 
> > 
> > This seems to be instructions to build a separate application? My original question was how to turn the archive into a more portable/unified nodec binary rather than running the ruby script directly. Essentially how to build this nodec/node-packer into an executable rather than how to use the source to build a separate app into an executable? Sorry if it wasn't clear. Thanks
> 
> Sorry, I think I misunderstood the question as well. Well, the original author managed to compiled it as an executable per README.md, but it has not been updated for 2 years or so and still points to earlier nodec 1.5.0 that bundles with Node.js 8.3.0.
> 
> I have no idea how to compile this into a binary file for Windows, macOS and Linux too.....

I was able to compile nodec v1.6.0 for Mac but was unable to do that in the same way for Windows. It's true having the new nodec would be helpful, but it's not a roadblock anymore. Using the steps provided by @slee047, I am able to compile my app on Windows, Mac and Linux - without any trouble.

**Comment by kgunnar** [comment]
> > > > > That would be awesome. It is important for me to be able to build the Windows version of nodec with updated runtime 8.15.1 and without the documentation, all my efforts have been in vain.
> > > > 
> > > > 
> > > > Before proceed on, I have assumed that you have installed the dependencies (SquashFS, Ruby and Python 2.7.x and added them into PATH environment variable)
> > > > Next, you will need to download the zip file (With 8.15.1 runtime):
> > > > https://github.com/slee047/node-packer/archive/1.6.0-8.15.1.zip
> > > > Then, you will extract this zip file to any folder (portable), for example, C:\nodec
> > > > Now, the entry path (Where executable is located) is at: C:\nodec\bin\nodec
> > > > The bat file is not really necessary if you have the SquashFS, and Ruby installed.
> > > > Subsequently, it is recommended for you to add the path (C:\nodec\bin) into PATH environment variable, so that your script can invoke this with 'nodec'.
> > > > Lastly, if you have a valid Node.js application (With package.json etc.), then it should compile the Node.js application with correct command use.
> > > > For start, I compile my Node.js application with this command:
> > > > ruby "nodec" --make-args=j8 -d "%TEMPPATH%" -r "%SRCPATH%" -o "%BINPATH%\output.exe" "%SRCPATH%\main.js"
> > > > Where:
> > > > 
> > > > * TEMPPATH = A temporary folder to store compilation cache, which takes several GBs.
> > > > * SRCPATH = Path to the root source code directory (Project directory)
> > > > * BINPATH = Path to the installed folder
> > > > 
> > > > And that:
> > > > 
> > > > * The Windows Node.js executable program is named as output.exe
> > > > * The entry point of this application is located on main.js
> > > 
> > > 
> > > This seems to be instructions to build a separate application? My original question was how to turn the archive into a more portable/unified nodec binary rather than running the ruby script directly. Essentially how to build this nodec/node-packer into an executable rather than how to use the source to build a separate app into an executable? Sorry if it wasn't clear. Thanks
> > 
> > 
> > Sorry, I think I misunderstood the question as well. Well, the original author managed to compiled it as an executable per README.md, but it has not been updated for 2 years or so and still points to earlier nodec 1.5.0 that bundles with Node.js 8.3.0.
> > I have no idea how to compile this into a binary file for Windows, macOS and Linux too.....
> 
> I was able to compile nodec v1.6.0 for Mac but was unable to do that in the same way for Windows. It's true having the new nodec would be helpful, but it's not a roadblock anymore. Using the steps provided by @slee047, I am able to compile my app on Windows, Mac and Linux - without any trouble.

Hi @saurabh-deep, would you mind posting the steps you took to build a nodec executable with ruby-packer on Mac? I tried before on a Linux machine without luck but I may have missed something and the steps for a Mac may illuminate that. Perhaps we can sort out Linux and possibly Windows for future reference. Thank you!

**Comment by saurabh-deep** [comment]
Exact steps mentioned here worked for me on macOS but on Windows it fails with compile-time errors - https://github.com/adobe/node-packer/blob/master/BUILD_INSTRUCTIONS.md

**Comment by slee047** [comment]
> Exact steps mentioned here worked for me on macOS but on Windows it fails with compile-time errors - https://github.com/adobe/node-packer/blob/master/BUILD_INSTRUCTIONS.md

Ok, I have tested and realized why node-packer simply cannot be compiled on Windows --> Because ruby-packer, the tool used to pack per Build_Instructions.md just did not work.

There are 2 ways to build node-packer, either building it with source of ruby-packer source (Download / Clone the repo and run the rubyc command) or the building it with compiled ruby-packer (0.4.0).

Before attempting to pack the node-packer via ruby-packer, I will attempt to create an executable ruby compiler.

Due to the dependencies of ruby-packer [https://github.com/pmq20/ruby-packer/blob/master/README.md](url) under **Building rubyc yourself**, I will be using cygwin as example.

1) Using packed ruby-packer binary executable:

An segmentation fault error occurs:

ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mswin64_140]

-- Control frame information -----------------------------------------------
c:0024 p:---- s:0141 e:000140 CFUNC  :initialize
c:0023 p:---- s:0138 e:000137 CFUNC  :open
c:0022 p:0027 s:0131 e:000130 BLOCK  E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1289 [FINISH]
c:0021 p:---- s:0127 e:000126 CFUNC  :open
c:0020 p:0019 s:0122 e:000121 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1288
c:0019 p:0084 s:0117 e:000116 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1256
c:0018 p:0076 s:0112 e:000111 BLOCK  E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:415 [FINISH]
c:0017 p:0010 s:0107 e:000106 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1387
c:0016 p:0013 s:0101 e:000100 BLOCK  E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390 [FINISH]
c:0015 p:---- s:0097 e:000096 CFUNC  :each
c:0014 p:0029 s:0093 e:000092 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389
c:0013 p:0044 s:0087 E:001be8 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:412
c:0012 p:0018 s:0078 e:000077 BLOCK  E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:390
c:0011 p:0046 s:0073 e:000072 BLOCK  E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1460
c:0010 p:0113 s:0068 e:000067 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1476
c:0009 p:0013 s:0061 e:000060 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1458
c:0008 p:0079 s:0055 e:000054 METHOD E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:389
c:0007 p:0065 s:0043 e:000042 METHOD E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:56
c:0006 p:0078 s:0036 e:000035 METHOD E:/__enclose_io_memfs__/local/lib/compiler.rb:136
c:0005 p:0052 s:0031 e:000030 METHOD E:/__enclose_io_memfs__/local/lib/compiler.rb:301
c:0004 p:0309 s:0024 e:000023 METHOD E:/__enclose_io_memfs__/local/lib/compiler.rb:82 [FINISH]
c:0003 p:---- s:0018 e:000017 CFUNC  :new
c:0002 p:0153 s:0012 E:0015c0 EVAL   /__enclose_io_memfs__/local/bin/rubyc:148 [FINISH]
c:0001 p:0000 s:0003 E:001dc0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/__enclose_io_memfs__/local/bin/rubyc:148:in `<main>'
/__enclose_io_memfs__/local/bin/rubyc:148:in `new'
E:/__enclose_io_memfs__/local/lib/compiler.rb:82:in `initialize'
E:/__enclose_io_memfs__/local/lib/compiler.rb:301:in `stuff_tmpdir'
E:/__enclose_io_memfs__/local/lib/compiler.rb:136:in `stuff_zlib'
E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:56:in `cp_r'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:389:in `cp_r'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1458:in `fu_each_src_dest'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1476:in `fu_each_src_dest0'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1460:in `block in fu_each_src_dest'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:390:in `block in cp_r'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:412:in `copy_entry'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1387:in `wrap_traverse'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:415:in `block in copy_entry'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1256:in `copy'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1288:in `copy_file'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1288:in `open'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1289:in `block in copy_file'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1289:in `open'
E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1289:in `initialize'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007FFF6945F714]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x93) [0x00007FFF65D483D3]
 [0x00007FF6F2093934]
 [0x00007FF6F20939B9]
 [0x00007FF6F1FCAE40]
 [0x00007FF6F2035026]
C:\WINDOWS\System32\ucrtbase.dll(seh_filter_exe+0x233) [0x00007FFF6626CFA3]
 [0x00007FF6F210CB00]
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll(_C_specific_handler+0xa0) [0x00007FFF3B91B900]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007FFF694646AF]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlWalkFrameChain+0x14bf) [0x00007FFF693C4BEF]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007FFF6946341E]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x200) [0x00007FFF693C9C90]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x40) [0x00007FFF693C9AD0]
 [0x00007FF6F1F8D1CE]
 [0x00007FF6F1F8A93E]
 [0x00007FF6F1FF1EDB]
 [0x00007FF6F1FF8E4B]
 [0x00007FF6F1F709C7]
 [0x00007FF6F1F730DA]
 [0x00007FF6F1FF7CEF]
 [0x00007FF6F1FF287B]
 [0x00007FF6F1FF79F2]
 [0x00007FF6F1FF279F]
 [0x00007FF6F1FC01A1]
 [0x00007FF6F1FC0002]
 [0x00007FF6F1FBFCCA]
 [0x00007FF6F1FBA656]
 [0x00007FF6F1FBB511]
 [0x00007FF6F1FDB274]
 [0x00007FF6F1FF637B]
 [0x00007FF6F1FC0545]
 [0x00007FF6F1FC1029]
 [0x00007FF6F1FC0C4D]
 [0x00007FF6F1FC3886]
 [0x00007FF6F1FC25C1]
 [0x00007FF6F1FB85B6]
 [0x00007FF6F1FB8394]
 [0x00007FF6F1FBE186]
 [0x00007FF6F1FBE130]
 [0x00007FF6F1F6C81D]
 [0x00007FF6F1FC0545]
 [0x00007FF6F1FC1029]
 [0x00007FF6F1FC0C4D]
 [0x00007FF6F1FC3886]
 [0x00007FF6F1FC25C1]
 [0x00007FF6F1FB85B6]
 [0x00007FF6F1FB8446]
 [0x00007FF6F1FC76FD]
 [0x00007FF6F1FBDA0C]
 [0x00007FF6F1FC13B0]
 [0x00007FF6F1FC3886]
 [0x00007FF6F1FC25C1]
 [0x00007FF6F1FB85B6]
 [0x00007FF6F1FB8394]
 [0x00007FF6F1FBE186]
 [0x00007FF6F1FBE130]
 [0x00007FF6F1FD1F83]
 [0x00007FF6F1FC0545]
 [0x00007FF6F1FC1029]
 [0x00007FF6F1FC0C4D]
 [0x00007FF6F1FC3886]
 [0x00007FF6F1FC25C1]
 [0x00007FF6F1FBFF36]
 [0x00007FF6F1FBFCCA]
 [0x00007FF6F1FBA656]
 [0x00007FF6F1FBB511]
 [0x00007FF6F1FDB274]
 [0x00007FF6F1FC0545]
 [0x00007FF6F1FC1029]
 [0x00007FF6F1FC0C4D]
 [0x00007FF6F1FC3886]
 [0x00007FF6F1FC25C1]
 [0x00007FF6F1F6EA5F]
 [0x00007FF6F1F6EAB9]
 [0x00007FF6F1F6ED30]
 [0x00007FF6F1F6111C]
 [0x00007FF6F210BE59]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007FFF674A7974]

-- Other runtime information -----------------------------------------------

* Loaded script: /__enclose_io_memfs__/local/bin/rubyc

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 encdb.so
    5 trans/transdb.so
    6 enc/windows_1252.so
    7 E:/__enclose_io_memfs__/lib/ruby/2.4.0/unicode_normalize.rb
    8 E:/__enclose_io_memfs__/lib/ruby/2.4.0/x64-mswin64_140/rbconfig.rb
    9 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/compatibility.rb
   10 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/defaults.rb
   11 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/deprecate.rb
   12 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/errors.rb
   13 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/version.rb
   14 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/requirement.rb
   15 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/platform.rb
   16 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/basic_specification.rb
   17 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/stub_specification.rb
   18 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/util/list.rb
   19 stringio.so
   20 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/specification.rb
   21 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/exceptions.rb
   22 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 E:/__enclose_io_memfs__/lib/ruby/2.4.0/monitor.rb
   24 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb
   26 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/dependency.rb
   27 E:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/path_support.rb
   28 E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb
   29 E:/__enclose_io_memfs__/local/lib/compiler/constants.rb
   30 E:/__enclose_io_memfs__/local/lib/compiler/error.rb
   31 E:/__enclose_io_memfs__/lib/ruby/2.4.0/shellwords.rb
   32 E:/__enclose_io_memfs__/lib/ruby/2.4.0/tmpdir.rb
   33 E:/__enclose_io_memfs__/lib/ruby/2.4.0/open3.rb
   34 E:/__enclose_io_memfs__/local/lib/compiler/utils.rb
   35 E:/__enclose_io_memfs__/lib/ruby/2.4.0/json/version.rb
   36 E:/__enclose_io_memfs__/lib/ruby/2.4.0/ostruct.rb
   37 E:/__enclose_io_memfs__/lib/ruby/2.4.0/json/generic_object.rb
   38 E:/__enclose_io_memfs__/lib/ruby/2.4.0/json/common.rb
   39 json/ext/parser.so
   40 json/ext/generator.so
   41 E:/__enclose_io_memfs__/lib/ruby/2.4.0/json/ext.rb
   42 E:/__enclose_io_memfs__/lib/ruby/2.4.0/json.rb
   43 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   44 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   45 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/common.rb
   46 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/generic.rb
   47 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ftp.rb
   48 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/http.rb
   49 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/https.rb
   50 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldap.rb
   51 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldaps.rb
   52 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/mailto.rb
   53 E:/__enclose_io_memfs__/lib/ruby/2.4.0/uri.rb
   54 date_core.so
   55 E:/__enclose_io_memfs__/lib/ruby/2.4.0/date.rb
   56 E:/__enclose_io_memfs__/lib/ruby/2.4.0/time.rb
   57 E:/__enclose_io_memfs__/lib/ruby/2.4.0/open-uri.rb
   58 E:/__enclose_io_memfs__/local/lib/compiler/gem_package.rb
   59 pathname.so
   60 E:/__enclose_io_memfs__/lib/ruby/2.4.0/pathname.rb
   61 E:/__enclose_io_memfs__/local/lib/compiler.rb
   62 E:/__enclose_io_memfs__/lib/ruby/2.4.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


2) Using the source code
/tmp/rubyc/ruby-2.6.0-0.6.0/squash_dirent.c: In function ‘squash_readdir’:
/tmp/rubyc/ruby-2.6.0-0.6.0/squash_dirent.c:148:14: error: ‘struct dirent’ has no member named ‘d_namlen’; did you mean ‘d_name’?
    sysentry->d_namlen = minsize;
              ^~~~~~~~
              d_name
make: *** [Makefile:419: squash_dirent.o] Error 1
make: *** Waiting for unfinished jobs....
Failed running [{"CI"=>"true", "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "CFLAGS"=>" -fPIC -O3 -fno-fast-math -ggdb3 -Os -fdata-sections -ffunction-sections -pipe  -I/tmp/rubyc/local/include  -I/tmp/rubyc/local/lib/libffi-3.2.1/include ", "LDFLAGS"=>" -L/tmp/rubyc/local/lib  /tmp/rubyc/local/lib/libz.a ", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "make -j4"]


So in any case, ruby-packer does not work in Windows regardless the earlier 0.4.0 release or the master branch. Therefore, node-packer cannot be compiled as a single executable at the moment

**Comment by saurabh-deep** [comment]
Thank you @slee047 for digging into it and coming to a conclusion. Appreciate it! 
So, like I mentioned earlier, I have been able to move forward with directly compiling my application binary with the desired code base of node-packer. Won't have been able to reach this far without your support.
