### ISSUE TITLE
浙江網絡不好，我只能寫了一個下載腳本。

### ISSUE THREAD

**Issue by zaoqi** [slee047/node-packer#7]
```bash
#!/bin/bash
for f in README.md LICENSE ROADMAP.md appveyor.yml HACKERS_GUIDE.md .gitignore .travis.yml bin/nodec lib/compiler.rb lib/compiler/constants.rb lib/compiler/error.rb lib/compiler/npm_package.rb lib/compiler/utils.rb tests/datetime tests/coffeescript_1 tests/coffeescript_2 ;do
  mkdir -p "$(dirname "$f")" ||exit
  pushd "$(dirname "$f")" ||exit
  [ -f "$(basename "$f")" ] || wget https://github.com/slee047/node-packer/raw/Series10/"$f" &
  popd ||exit
done
wait

if [ ! -d node ] ;then

NODEVER="$(grep NODEVER= .travis.yml | sed 's|^.*=\([0-9.]*\)$|\1|g')"
rm -fr node-v$NODEVER libsquash libautoupdate node
wget -O - https://nodejs.org/dist/v$NODEVER/node-v$NODEVER.tar.gz | tar -xzv
git clone --depth 1 https://github.com/pmq20/libsquash.git
git clone --depth 1 https://github.com/pmq20/libautoupdate.git

mv node-v$NODEVER node/
rm -rf node/deps/libsquash && cp -R ./libsquash node/deps/libsquash && rm -rf node/deps/libsquash/.git && rm node/deps/libsquash/.gitignore && rm node/deps/libsquash/sample/enclose_io_main.c && mv node/deps/libsquash/sample/enclose_io_libsquash.gyp node/deps/libsquash/enclose_io_libsquash.gyp
rm -rf node/deps/libautoupdate && cp -R ./libautoupdate node/deps/libautoupdate && rm -rf node/deps/libautoupdate/.git && rm node/deps/libautoupdate/.gitignore
find node -name .gitignore -exec rm {} \;
rm -rf node/deps/npm

rm -fr node-v$NODEVER libsquash libautoupdate

fi

chmod +x ./bin/nodec
```

**Comment by zaoqi** [comment]
然後...
```
 ./bin/nodec --npm-package=typescript
Node.js Compiler (nodec) v1.6.0
- entrance: not provided, a single Node.js interpreter executable will be produced.
- HINT: call nodec with --help to see more options and use case examples
- options: {:npm_package=>"typescript", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"/home/zaoqi/nodec/a.out", :tmpdir=>"/tmp/nodec", :npm_package_version=>"latest"}

=== WARNING ===
Please make sure to have installed the correct version of node in your environment.
It should match the enclosed Node.js runtime version of the compiler.
Expecting v10.15.3; yet got v11.13.0.

-> mkdir -p /tmp/nodec
-> cp -r "/home/zaoqi/nodec/node" "/tmp/nodec/node-10.15.3-1.6.0"
-> rm -rf /tmp/nodec/typescript-latest
-> mkdir -p /tmp/nodec/typescript-latest
-> cd /tmp/nodec/typescript-latest
-> cd /home/zaoqi/nodec
-> cd /tmp/nodec/__work_dir__/__enclose_io_memfs__
Traceback (most recent call last):
	4: from ./bin/nodec:157:in `<main>'
	3: from /home/zaoqi/nodec/lib/compiler.rb:182:in `run!'
	2: from /home/zaoqi/nodec/lib/compiler.rb:238:in `npm_package_set_entrance'
	1: from /home/zaoqi/nodec/lib/compiler/utils.rb:46:in `chdir'
/home/zaoqi/nodec/lib/compiler/utils.rb:46:in `chdir': No such file or directory @ dir_chdir - /tmp/nodec/__work_dir__/__enclose_io_memfs__ (Errno::ENOENT)
```

**Comment by slee047** [comment]
2 Problems / 两个问题
1) Installed (Default) Node.js does not match / 所安装（默认）的 Node.js 版本不匹配

=== WARNING ===
Please make sure to have installed the correct version of node in your environment.
It should match the enclosed Node.js runtime version of the compiler.
Expecting v10.15.3; yet got v11.13.0.

It seemed like you have installed Node.js 11.13.0, and node-packer is not going to support odd number (Non-Long Term Support, LTS) release. So, please install Node.js 10.15.3 and ensure that this is the default Node.js version in PATH environment variable instead.

看来你已经安装 Node.js 11.13.0，然而 node-packer 将不支持单数 （非长期支持，LTS）发布。因此，请安装 Node.js 10.15.3 并确保这是在 PATH 环境变量下默认的 Node.js 版本。


2) Lack of Ruby Compiler / 缺失 Ruby 编译器

-> cd /tmp/nodec/__work_dir__/__enclose_io_memfs__
Traceback (most recent call last):
	4: from ./bin/nodec:157:in `<main>'
	3: from /home/zaoqi/nodec/lib/compiler.rb:182:in `run!'
	2: from /home/zaoqi/nodec/lib/compiler.rb:238:in `npm_package_set_entrance'
	1: from /home/zaoqi/nodec/lib/compiler/utils.rb:46:in `chdir'
/home/zaoqi/nodec/lib/compiler/utils.rb:46:in `chdir': No such file or directory @ dir_chdir - /tmp/nodec/__work_dir__/__enclose_io_memfs__ (Errno::ENOENT)

You will need to install Ruby compiler yourself. On Linux, it should be installed. On macOS, please use Homebrew to install Ruby.  Also, try the command _ruby -v_ to see if you have Ruby installed or not. I know that Ruby 2.5.x works without issue but I have not used the earlier or 2.6.x versions.

Note: On Windows, Ruby compiler can be found here: [https://rubyinstaller.org/](url)

你需要自行安装 Ruby 编译器。在 Linux 下应该已经安装了。在 macOS，请使用家酿 (Homebrew) 安装 Ruby。另外，尝试命令 _ruby -v_ 以便确认 Ruby 是否安装。我知道 Ruby 2.5.x 能正常使用，但我没使用过早期或者 2.6.x 版本。

注: 在 Windows, Ruby 编译器的下载地址: [https://rubyinstaller.org/](url)
