### ISSUE TITLE
请问一下egg怎么打包啊

### ISSUE THREAD

**Issue by huyu1** [slee047/node-packer#9]
不知道为啥，打包进去的只有egg-bin获取egg-scripts，源代码打包不进去

**Comment by slee047** [comment]
Translation based on huyu1's question: I don't know why only egg-scripts retrieved from egg-bin can be packed, source code could not be packed?

My reply: Sorry, I don't understand your question. Are you trying to pack projects that are written in Python?

 我的回复：很抱歉，我不明白你的问题。你是否试图将基于 Python 的项目代源码打包？

**Comment by huyu1** [comment]
**抱歉，说的不够仔细，就是打包node的框架egg.js,不能正常打包，最简单的项目可以直接npm建出来https://eggjs.org/zh-cn/core/deployment.html，但是不知道为什么，不管怎么配置都无法把源码打包进去

**Comment by huyu1** [comment]
如果可以的话你可以帮我试试怎么打包吗，配置文件怎么写？

**Comment by slee047** [comment]
Translation: Apologies, it is not clear. It just happened that Node Framework module egg.js cannot be packed normally, the minimum (simplest) project can be built from npm [https://eggjs.org/en/core/deployment.html](url), but for unknown reason why regardless how the configuration was done, the source code simply cannot be packed.

If possible, could you help me try to see how to pack this and how to write its configuration file?

My reply: Ok, let's be clear. Did a binary executable (packed) file generated but it just cannot run? Or were there any errors during the compilation? I suspect that your issue might be related to [https://github.com/slee047/node-packer/issues/8](url) and therefore you should download and use the latest release [https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1](url) **AND** add _--clean-tmpdir_ argument during the first pack in order to delete the cache folder (This will increase the pack time but it will apply the fix for this issue).

我的回复：首先弄清楚。是否有个可执行文件 （打包）文件生成，但是它始终无法运行？还是在编译（打包）的过程中报错？我怀疑你这个情况可能与 [https://github.com/slee047/node-packer/issues/8](url) 有关联，因此你应该下载并使用最新版 [https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1](url) **并且** 在首次打包时增加 _--clean-tmpdir_ 参数以便删除缓存目录（这会增加打包时间，但却可以修正此问题）。

**Comment by VincentWuShiChao** [comment]
@huyu1 
我也是打包生成的a.out能执行，但是只限在项目根目录下执行能成功，放到单独的一个目录就是缺各种文件，貌似是源码没有打包进去

**Comment by msmao** [comment]
用 https://github.com/eggjs/examples.git 的 helloworld 案例生成 a.out 在 helloworld 根目录下确实可以执行成功；但是 把 a.out 复制到 单独的目录，却无法执行。是否有部分代码没有被打包进去？

以下是日志：

----

fg:helloworld jian$ ls
app			node_modules		package.json
config			package-lock.json	test
fg:helloworld jian$ /Users/jian/Downloads/node-packer-1.6.0-10.16.3/bin/nodec node_modules/egg-bin/bin/egg-bin.js -d ./
Node.js Compiler (nodec) v1.6.0
- entrance: /Users/jian/Downloads/examples/helloworld/node_modules/egg-bin/bin/egg-bin.js
- options: {:tmpdir=>"/Users/jian/Downloads/examples/helloworld", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"/Users/jian/Downloads/examples/helloworld/a.out"}

-> mkdir -p /Users/jian/Downloads/examples/helloworld
-> cp -r "/Users/jian/Downloads/node-packer-1.6.0-10.16.3/node" "/Users/jian/Downloads/examples/helloworld/node-10.16.3-1.6.0"
-> rm -rf /Users/jian/Downloads/examples/helloworld/__work_dir__
-> mkdir -p /Users/jian/Downloads/examples/helloworld/__work_dir__
-> cp -r "/Users/jian/Downloads/examples/helloworld/node_modules/egg-bin" "/Users/jian/Downloads/examples/helloworld/__work_dir__/__enclose_io_memfs__"
-> cd /Users/jian/Downloads/examples/helloworld/__work_dir__/__enclose_io_memfs__
-> Running ["npm -v"]
6.9.0
-> Running ["npm install --production"]
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 

> fsevents@1.2.9 install /Users/jian/Downloads/examples/helloworld/__work_dir__/__enclose_io_memfs__/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/jian/Downloads/examples/helloworld/__work_dir__/__enclose_io_memfs__/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> core-js@2.6.9 postinstall /Users/jian/Downloads/examples/helloworld/__work_dir__/__enclose_io_memfs__/node_modules/core-js
> node scripts/postinstall || echo "ignore"

// 省略中间部分过程...

 -lm
rm bc3229a6446da46cf9898d5c1b4b9e231399e74f.intermediate 72f6237eaa5559d4e49fd927b3d09b9d92a9e427.intermediate 5745f35e5139b61ee8c1cc506b1e84ba963fe2cd.intermediate
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
-> cd /Users/jian/Downloads/examples/helloworld
-> cp "/Users/jian/Downloads/examples/helloworld/node-10.16.3-1.6.0/out/Release/node" "/Users/jian/Downloads/examples/helloworld/a.out"
fg:helloworld jian$ ls
__work_dir__		config			package-lock.json
a.out			node-10.16.3-1.6.0	package.json
app			node_modules		test
fg:helloworld jian$ ./a.out 
Usage: egg-bin [command] [options]

命令：
  a.out completion  generate bash completion script
  a.out autod       Generate pkg.dependencies and pkg.devDependencies automatically
  a.out cov         Run test with coverage
  a.out debug       Start server at local debug mode
  a.out dev         Start server at local dev mode
  a.out pkgfiles    Generate pkg.files automatically
  a.out test        Run test with mocha

Global Options:
  -h, --help     显示帮助信息                                                                                     [布尔]
  -v, --version  显示版本号                                                                                       [布尔]

选项：
  --typescript, --ts     whether enable typescript support, will load `ts-node/register` etc                      [布尔]
  --declarations, --dts  whether create dts, will load `egg-ts-helper/register`                                   [布尔]
fg:helloworld jian$ ./a.out dev
2019-08-28 17:11:41,024 INFO 93734 [master] node version v10.16.3
2019-08-28 17:11:41,026 INFO 93734 [master] egg version 1.19.0
2019-08-28 17:11:41,469 INFO 93734 [master] agent_worker#1:93738 started (440ms)
2019-08-28 17:11:42,023 INFO 93734 [master] egg started on http://127.0.0.1:7001 (997ms)
^C2019-08-28 17:11:52,559 INFO 93734 [master] receive signal SIGINT, closing
fg:helloworld jian$ ls
__work_dir__		logs			package.json
a.out			node-10.16.3-1.6.0	run
app			node_modules		test
config			package-lock.json
fg:helloworld jian$ cd ..
fg:examples jian$ ls
LICENSE			framework		passport
README.md		hackernews		progressive
assets-with-roadhog	hackernews-async	redefine-controller
assets-with-umi		hackernews-async-ts	schedule
bin			hackernews-async-ts-di	sequelize
bodyParser		hackernews-datahub	sequelize-ts
cnode-api		helloworld		sofa-rpc
cnode-api-async		httpclient		static
cookie			ipc			todomvc
cookie-session		middleware		unittest
custom-env		multipart		unittest-jest
download		multipart-file-mode	view-nunjucks
example.js		package.json
fg:examples jian$ cd helloworld/
fg:helloworld jian$ ls
__work_dir__		logs			package.json
a.out			node-10.16.3-1.6.0	run
app			node_modules		test
config			package-lock.json
fg:helloworld jian$ cp a.out ./../
fg:helloworld jian$ cd ..
fg:examples jian$ ls
LICENSE			example.js		package.json
README.md		framework		passport
a.out			hackernews		progressive
assets-with-roadhog	hackernews-async	redefine-controller
assets-with-umi		hackernews-async-ts	schedule
bin			hackernews-async-ts-di	sequelize
bodyParser		hackernews-datahub	sequelize-ts
cnode-api		helloworld		sofa-rpc
cnode-api-async		httpclient		static
cookie			ipc			todomvc
cookie-session		middleware		unittest
custom-env		multipart		unittest-jest
download		multipart-file-mode	view-nunjucks
fg:examples jian$ ./a.out 
Usage: egg-bin [command] [options]

命令：
  a.out completion  generate bash completion script
  a.out autod       Generate pkg.dependencies and pkg.devDependencies automatically
  a.out cov         Run test with coverage
  a.out debug       Start server at local debug mode
  a.out dev         Start server at local dev mode
  a.out pkgfiles    Generate pkg.files automatically
  a.out test        Run test with mocha

Global Options:
  -h, --help     显示帮助信息                                                                                     [布尔]
  -v, --version  显示版本号                                                                                       [布尔]

选项：
  --typescript, --ts     whether enable typescript support, will load `ts-node/register` etc                      [布尔]
  --declarations, --dts  whether create dts, will load `egg-ts-helper/register`                                   [布尔]
fg:examples jian$ ./a.out dev
Error: egg is not found in /Users/jian/Downloads/examples/node_modules
    at assertAndReturn (/__enclose_io_memfs__/node_modules/egg-utils/lib/framework.js:66:9)
    at Object.getFrameworkPath (/__enclose_io_memfs__/node_modules/egg-utils/lib/framework.js:49:10)
    at DevCommand.formatArgs (/__enclose_io_memfs__/lib/cmd/dev.js:89:28)
    at formatArgs.next (<anonymous>)
    at onFulfilled (/__enclose_io_memfs__/node_modules/co/index.js:65:19)
    at /__enclose_io_memfs__/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/__enclose_io_memfs__/node_modules/co/index.js:50:10)
    at toPromise (/__enclose_io_memfs__/node_modules/co/index.js:118:63)
    at next (/__enclose_io_memfs__/node_modules/co/index.js:99:29)
fg:examples jian$

**Comment by slee047** [comment]
你好 msmao，
我怀疑这个问题与下面的报告有关联：
https://github.com/slee047/node-packer/issues/11


请问你是用什么 OS（macOS
 还是 Linux 的什么发行版？版本？）以及所使用的编译器（GCC G++ 还是 clang clang++？以及 make） 版本以便更好的了解情况。

如果方便的话，请在 Windows 下使用 Visual Studio 2017 (不兼容 2019) 试试看这个问题是否还在。感谢谅解。




Translations:

Hi msmao, I suspect that what you have reported above is related to this issue:

https://github.com/slee047/node-packer/issues/11


Could you please provide your OS (macOS? Or which Linux distro and its version) as well as the version of compiler used (GCC G++ or clang clang++ as well as make) in order to better understand the issue.


If possible, please try this in Windows with Visual Studio 2017 (VS 2019 is not supported) to confirm if this issue also happens or not. Thank you for your understanding.

**Comment by msmao** [comment]
你好 @slee047 ，

之前用 macOS Mojave 10.14.5 (18F203) 自带的 gcc，没有 Windows 环境

### fg:Downloads jian$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
### fg:Downloads jian$ g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
### fg:Downloads jian$ clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
### fg:Downloads jian$ clang++ -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

--------

后安装 gcc@4.9 

`
brew install gcc@4.9 
vim ~/.bash_profile
alias gcc="gcc-4.9"
alias g++="g++-4.9"
alias cc="gcc-4.9"
alias c++="c++-4.9"
alias clang="gcc-4.9"
`

保存，并重启终端，再执行 nodec 命令结果也是一样的

### fg:helloworld jian$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc-4.9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
Target: x86_64-apple-darwin17.3.0
Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.4 (Homebrew GCC 4.9.4_1) 
### fg:helloworld jian$ g++ -v
Using built-in specs.
COLLECT_GCC=g++-4.9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
Target: x86_64-apple-darwin17.3.0
Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.4 (Homebrew GCC 4.9.4_1) 
### fg:helloworld jian$ clang -v
Using built-in specs.
COLLECT_GCC=gcc-4.9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
Target: x86_64-apple-darwin17.3.0
Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.4 (Homebrew GCC 4.9.4_1)

**Comment by slee047** [comment]
> 你好 @slee047 ，
> 
> 之前用 macOS Mojave 10.14.5 (18F203) 自带的 gcc，没有 Windows 环境
> 
> ### fg:Downloads jian$ gcc -v
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> ### fg:Downloads jian$ g++ -v
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> ### fg:Downloads jian$ clang -v
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> ### fg:Downloads jian$ clang++ -v
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> 后安装 gcc@4.9
> 
> `brew install gcc@4.9 vim ~/.bash_profile alias gcc="gcc-4.9" alias g++="g++-4.9" alias cc="gcc-4.9" alias c++="c++-4.9" alias clang="gcc-4.9"`
> 
> 保存，并重启终端，再执行 nodec 命令结果也是一样的
> 
> ### fg:helloworld jian$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc-4.9
> COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
> Target: x86_64-apple-darwin17.3.0
> Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
> Thread model: posix
> gcc version 4.9.4 (Homebrew GCC 4.9.4_1)
> 
> ### fg:helloworld jian$ g++ -v
> Using built-in specs.
> COLLECT_GCC=g++-4.9
> COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
> Target: x86_64-apple-darwin17.3.0
> Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
> Thread model: posix
> gcc version 4.9.4 (Homebrew GCC 4.9.4_1)
> 
> ### fg:helloworld jian$ clang -v
> Using built-in specs.
> COLLECT_GCC=gcc-4.9
> COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@4.9/4.9.4_1/libexec/gcc/x86_64-apple-darwin17.3.0/4.9.4/lto-wrapper
> Target: x86_64-apple-darwin17.3.0
> Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@4.9/4.9.4_1 --libdir=/usr/local/Cellar/gcc@4.9/4.9.4_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 4.9.4_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues MAKEINFO=missing --disable-nls --enable-multilib
> Thread model: posix
> gcc version 4.9.4 (Homebrew GCC 4.9.4_1)
您好，可否使用 Node.js 10.15.3 和 Nodec 10.15.3 再尝试打包？
Hi, could you try compiling this again with Node.js 10.15.3 and Nodec 10.15.3?

Nodec 10.15.3 下载地址 / Download link：
[https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1](https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1)
